# Generated by Django 5.0 on 2024-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Verification'),
        ),
    ]
