# Generated by Django 5.0 on 2023-12-07 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='Mailing time')),
                ('periodicity', models.CharField(choices=[('daily', 'Once a day'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], max_length=12, verbose_name='Periodicity')),
                ('mailing_status', models.CharField(max_length=24, verbose_name='Mailing status')),
            ],
            options={
                'verbose_name': 'Mailing list',
                'verbose_name_plural': 'Mailign lists',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('status', models.CharField(max_length=24, verbose_name='Status')),
                ('server_response', models.TextField(verbose_name='Server response')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailinglist')),
            ],
            options={
                'verbose_name': 'Mailing log',
                'verbose_name_plural': 'Mailing logs',
            },
        ),
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='E-mail subject')),
                ('body', models.TextField(verbose_name='E-mail body')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.mailinglist')),
            ],
            options={
                'verbose_name': 'Mailing message',
                'verbose_name_plural': 'Mailing messages',
            },
        ),
    ]
