# Generated by Django 5.0 on 2023-12-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'Mailing list', 'verbose_name_plural': 'Mailing lists'},
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mailings.client'),
        ),
    ]
