# Generated by Django 5.0 on 2023-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AddField(
            model_name='settings',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting date'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mailing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Mailing time'),
        ),
    ]
