# Generated by Django 5.0 on 2024-01-03 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_message_options_alter_settings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date & Time')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished')], max_length=24, verbose_name='Status')),
                ('server_response', models.TextField(verbose_name='Server response')),
                ('email_subject', models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Subject')),
                ('email_body', models.TextField(blank=True, null=True, verbose_name='Email Body')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.client')),
            ],
            options={
                'verbose_name': 'Mailing log',
                'verbose_name_plural': 'Mailing logs',
            },
        ),
    ]
