# Generated by Django 5.0 on 2023-12-11 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailinglist_options_mailinglist_client'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingMessage',
            new_name='Message',
        ),
    ]
