# Generated by Django 5.0 on 2023-12-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_rename_mailingmessage_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='client',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='message',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailings.client', verbose_name='Client'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='Mailing time')),
                ('periodicity', models.CharField(choices=[('daily', 'Once a day'), ('weekly', 'Once a week'), ('monthly', 'Once a month')], max_length=12, verbose_name='Periodicity')),
                ('mailing_status', models.CharField(max_length=24, verbose_name='Mailing status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='mailings.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Mailing list',
                'verbose_name_plural': 'Mailing lists',
            },
        ),
        migrations.DeleteModel(
            name='MailingLog',
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
    ]
