# Generated by Django 5.0 on 2024-01-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('article', models.CharField(max_length=512, verbose_name='Article')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Blog Image')),
                ('number_of_view', models.PositiveIntegerField(default=0, verbose_name='Number of Views')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
